### ISSUE TITLE
Move bacardi.cc path to core.gypi?

### ISSUE THREAD

**Issue by hwanseung** [lunchclass/bacardi#104]
present bacardi.cc file is auto generated.
actually it is related with idl files. so bacardi.cc path was wrote in example.gypi for gyp build.
(https://github.com/lunchclass/bacardi/blob/master/examples/examples.gypi#L29)

it means bacardi user have to write bacardi.cc file path in their's gypi files.
is it fine? or should we move to that files to core.gypi?
i think it is better to hide auto-genreated files to user.

cc @romandev , @yjaeseok, @daehyunjimmy

**Comment by romandev** [comment]
Seems reasonable to me.
But I'm not sure if it should be move to core.
Because the core directory only have C++ core implementation and not generated binding.
So, can we move it to binding.gyp instead?

**Comment by romandev** [comment]
WDYT?

**Comment by hwanseung** [comment]
it is looks like better to move binding.gyp instead of core.gypi.
i will make patch.

**Comment by hwanseung** [comment]
This issue was resolved.
