### ISSUE TITLE
Tests are not working in CI tools.

### ISSUE THREAD

**Issue by hwanseung** [lunchclass/bacardi#138]
Tests are not working in CI tools.
after meged #135 CL, tests were passed in CI tools.
because SimRank codes did not formatting like us coding style.
so when run `./bacardi test` command, it just show message for formatting and skip the tests.

**Comment by hwanseung** [comment]
i think there are two ways to resolve this issue.
first. except SimRank path when check formatting.
second. reformatting SimRank codes.

second is too easy to resolve. but i think first solution is better.
because SimRanck is not our project. so i don't want to touch SimRank codes.
we have to know how to except some path when formatting.
how do you think? @romandev @yjaeseok

**Comment by romandev** [comment]
@hwanseung IMHO, the SimRank algorithm is external code, so, I didn't reformat them.
To resolve this issue, we have two options as follows:
- Just formatting them
- Find a way to ignore them

Also, we should change that ```./bacardi format``` returns zero as error code even if there are some reformatable codes.

**Comment by romandev** [comment]
Fixed in #140
