### ISSUE TITLE
Auto execute format and test If needed

### ISSUE THREAD

**Issue by yjaeseok** [lunchclass/bacardi#152]
Our test command now exits with a "You should run |bacardi format| command first." message if format is required.

This means that the user must explicitly type the ```bacardi format``` and type the ```bacardi test``` again, which is very annoying.

And some test case failed in AppVeyor if need format.
please refer to link
https://ci.appveyor.com/project/romandev/bacardi/build/1.0.257/job/e32eve5hgrivpnkj

So I would like to suggest is that if we need bacardi format when you type bacardi test, we execute format and test automatically?

As a result, user cannot see "You should run |bacardi format| command first" message and user can test by typing ```bacardi test``` only.

**Comment by romandev** [comment]
I thought that someone might not want to format in development.
For examples, someone might not like this style for some reasons (e.g. too short line-break).
So, I think it's better to separate checking formatting from ```./bacardi test```. WDYT?

**Comment by yjaeseok** [comment]
So how about providing a command to force and test format, like clean build?

2017. 11. 1. 오후 5:35에 "Jinho Bang" <notifications@github.com>님이 작성:

**Comment by yjaeseok** [comment]
Hmm okay.

But I think we should fix AppVeyor testing issue.

I think we should run ```./bacardi format``` before ```./bacardi test``` for CI results.

Please refer below AppVeyor results
https://ci.appveyor.com/project/romandev/bacardi/build/1.0.257/job/e32eve5hgrivpnkj

**Comment by hwanseung** [comment]
if checking format process separate from test command,
we have to run `./bacardi format` before `./bacardi test` in for CI tools.

we would like to merge same formatting code.
so if new patch were not keep our formatting, CI tools result should be fail.

what problem does have at your link AppVeyor results?
i think if that patch were not keep our formatting, that result is correct.

CI tools is not just to check pass tests. we also have to check formatting automatically before merge.

but it seems weird to show that message which is "You should run |bacardi format| command first" in test command.
if checking format process separate from test command, that problem will be resolved.

**Comment by yjaeseok** [comment]
Ahhh.....

I am so sorry. 

This issue is all due to my misunderstanding. In fact, I know that the role of the format command is the purpose for formatting :(.  And I thought format was the same command as clean. 

So I mistakenly thought that AppVeyor could cause an error if there were any remaining elements in the previous patch before testing. OMG !! 

Anyway, now I understood everything through hwanseung's comment and code.

I think there is an issue inside of me!!
I am sorry @romandev and @hwanseung

**Comment by romandev** [comment]
@yjaeseok but do we need a new issue or reopening this issue to separate ```./bacardi format(or lint?)``` from ```./bacardi test```.
