### ISSUE TITLE
Separate test and format command in develop

### ISSUE THREAD

**Issue by yjaeseok** [lunchclass/bacardi#155]
I would like to propose to separate ```./bacardi test``` and ```./bacardi format``` 
commands in develop environment.
Because we generally do not want to check formatting during test.
In other words, most of the developers just want to ```test``` it only.

So, I will separate ```./bacardi test``` and ```./bacardi format.```
Because the AppVeyor test should run format test for fixing formatting error,
I will change AppVeyor test with run format test.

As a result, developers can test only test command.
Also when developer want to PR, they must be fixed formatting issue (because of AppVeyor).

How do you think @romandev , @hwanseung , @byeolbit  ?

**Comment by romandev** [comment]
I think we need the following things:
```./bacardi test```
```./bacardi lint```
```./bacardi format```

**Comment by yjaeseok** [comment]
PTAL !! @byeolbit

**Comment by hwanseung** [comment]
@romandev 
what is difference between lint and format command?

**Comment by byeolbit** [comment]
@yjaeseok I agree to separate `./bacardi format` command from `./bacardi test`
Then, do developers have to check formatting issue before PR?
If so, do they can notice their unformatted code after run AppVeyor?

**Comment by yjaeseok** [comment]
@byeolbit Yes they can get an error in AppVeyor environment, when there is an unformatted code.
