### ISSUE TITLE
Add lint command color highlight

### ISSUE THREAD

**Issue by yjaeseok** [lunchclass/bacardi#164]
When executing the lint command, highlight is removed,
So lint result is not readable.

**Comment by romandev** [comment]
@yjaeseok Is this good-first-bug? clang-format (not lint) provides the option?

**Comment by romandev** [comment]
If so, it's better to describe how to do it in details if possible.

**Comment by yjaeseok** [comment]
Okay  I will add description more detail

**Comment by nadongguri** [comment]
I will take this issue.

**Comment by yjaeseok** [comment]
The currently implemented ```./bacardi lint``` command saves the result of ```./bacardi format --diff``` in the result variable. And then print out the value of result.

For the above reasons,
The text result of ```/bacardi format --diff``` and ```./bacardi lint``` is the same as the text output, 
But the color highlight is different.

I think it seems to be good for readability with color highlight 
when user types ```./bacardi lint``` also.

So I suggest to make color highlight in ```./bacardi lint``` command

**Comment by nadongguri** [comment]
@yjaeseok, I have a question. In order to highlight the result of lint, do I have to make it out modifying echo command or command "bacardi format --diff" to print out?

**Comment by yjaeseok** [comment]
@nadongguri, Yes I think. if you can run format command once, please run just one time. 
If you can`t that`s okay. It is not important

**Comment by yjaeseok** [comment]
@nadongguri Thank you for your contribution
