### ISSUE TITLE
Current camelcase filter doesn't recognize some type name which has space

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#168]
Current camelcase filter doesn't recognize some type name which has space.

For example, if the type name is `unsigned short`,
we expect the result of the filter with `unsigned short` as follows:
`UnsignedShort`
But actually got,
`Unsigned short`

**Comment by hwanseung** [comment]
um.. i found that camel case is normally to distinguish with upper camel case and lower camel case.
according to wikipedia(https://en.wikipedia.org/wiki/Camel_case), 
camel case is usually means lower camel case.
and there is other term to distinguish with upper camel case and lower camel case.
it is pascal case(https://en.wikipedia.org/wiki/PascalCase).

so i think we have to change terms to distinguish clearly.

**Comment by hwanseung** [comment]
i will take this issue.
