### ISSUE TITLE
Explain lint command and pr command in README.md

### ISSUE THREAD

**Issue by hwanseung** [lunchclass/bacardi#177]
lint and command and pr command was added.
these command are not in README.md.
so explain two command in README.md

**Comment by nadongguri** [comment]
@taxookim, good first bug.

**Comment by nadongguri** [comment]
@hwanseung, I guess @taxookim is busy of contributing the absolute project. I will handle it. :)

**Comment by romandev** [comment]
I'm not sure if it's a right thing that `lint` command should be exposed to users.

If there are some lint errors, users can run ./bacardi format command.
So, all lint errors will be fixed. Then, why do we need to expose `./bacardi lint` command to user?

If `./bacardi format` comand doesn't cover all lint errors, it should be exposed. But now I do not think there is a good reason to expose it. IMHO, it's better to expose a small number of things to users if possible.

**Comment by romandev** [comment]
Also, I think `pr` command should be updated but it's better to separate document from README.md.
(e.g. contributing guide)
