### ISSUE TITLE
Unexpected text print out when running `./bacardi`

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#204]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites
* [ ] Are you running the latest version?

### Description
Unexpected text printed.

### Steps to Reproduce
`./bacardi`

**Expected behavior:** [What you expect to happen]
Should not print the following text:
```
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
```
It can be different on each platforms.

**Actual behavior:** [What actually happens]
Print the above text.

### Operating System
* [x] Linux (x86/x64)
* [x] OSX (x86/x64)
* [x] Windows (x86/x64)

**Comment by nadongguri** [comment]
@romandev, I will add that feature.

**Comment by nadongguri** [comment]
@romandev, 
Windows : Usage: C:\bacardi\\THIRD_~1\win-bash\basename.exe name [suffix] ?
Linux : 
basename: missing operand
Try 'basename --help' for more information.
