### ISSUE TITLE
Windows build support.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#26]
We should add support for windows build.

**Comment by hwanseung** [comment]
i tried to build at windows. but there is a problem.
after unzip the node.js, it returned 50 error instead of 0.
so it can't pass to next steps.
i tried to build again after changed old version download url. 
and it returned 0 normally.
but nightly version was returned 50 error too.

actually i don't know what 50 error means.
is there anyone to know 50 error's mean in win-unzip?

**Comment by hwanseung** [comment]
maybe i found mean of 50 error. (http://www.info-zip.org/mans/unzip.html - DIAGNOSTICS)
according to that url, my computer spaces was not affordable to unzip.

**Comment by romandev** [comment]
I know the issue. It happens because the filename(including its fullpath) is too long.
(As I know, in windows, it should be < 255? for a historical reason such as MS-DOS)

In the current implementation, although we are extracting in C:\tmp_{random_number} [1], the error occurs.
So, the path should be shorter. FYI, when I tried it in C:\node (length 7), it's succeeded.

[1] https://github.com/lunchclass/bacardi/blob/master/bootstrap/common/sync_third_party.sh#L45

**Comment by romandev** [comment]
Very good!

**Comment by yjaeseok** [comment]
Cool!!!

**Comment by yjaeseok** [comment]
Hmm.. T.T
I got some error in My Windows.

C:\Users\Jake\workspace\yjaeseok\bacardi>if not defined npm_config_node_gyp (node "C:\Users\Jake\WORKSP~1\yjaeseok\bacar
di\THIRD_~1\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "
" rebuild )
The system cannot find the path specified.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Jake\WORKSP~1\yjaeseok\bacardi\THIRD_~1\node\node_modules\npm\node
_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\Jake\\workspace\\yjaeseok\\bacardi\\third_party\\node\\node.exe" "C:\\Users\\Jake\\WORKSP~1
\\yjaeseok\\bacardi\\THIRD_~1\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jake\workspace\yjaeseok\bacardi
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the undefined install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jake\AppData\Roaming\npm-cache\_logs\2017-09-11T17_41_57_791Z-debug.log

**Comment by yjaeseok** [comment]
Should I install Node.js first?

**Comment by romandev** [comment]
Ah, really? what happens?
Hmm, could you try it in c:\bacardi again?
The Windows system can not support looooong path name (it should be < 255).
So, sometimes it can make a trouble in deeper directory.

**Comment by romandev** [comment]
@yjaeseok, @hwanseung Please check your emails. I added you guys to Bacardi project members.

**Comment by romandev** [comment]
Also, you MUST run the bacardi command on CMD or PowerShell with Administrator permission.
You can usually find it CMD's context menu (right click menu).

**Comment by yjaeseok** [comment]
Oh.. sorry, this issue about my mistake!.
I should run CMD as an Administrator permission.

After run CMD as an Administrator permission, it works fine. 
(But, I do not have Visual studio, it takes too many times)

**Comment by romandev** [comment]
Can we close this issue?

**Comment by hwanseung** [comment]
there is one left issue.
it is not still work to use clean command in AppVeyor.

**Comment by hwanseung** [comment]
@romandev 
i think this issue was resolved and we can close this issue now, but i don't have authority to close this issue. could you change status of this issue?

**Comment by romandev** [comment]
@hwanseung I've just given the permission. I didn't know that.. Sorry :P

**Comment by hwanseung** [comment]
finally i got a authority to change status of issue. and i will close this issue.
