### ISSUE TITLE
Introduce C++ lint and formatter tool.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#3]
We should introduce C++ lint and automatic formatter tool.

**Comment by sunglim** [comment]
Once `.clang-format` with chromium-style format is landed, then we can use `git clang-format` tool.
In other word, `.clang-format` on root directory is the only thing required.

**Comment by romandev** [comment]
@sunglim, Thank you for the guide!

FYI, we are using ```./bacardi format``` command instead of ```git clang-format```.
But it's better to put the .clang-format file on root directory instead of hard-coding.
