### ISSUE TITLE
CalculatorExample: Add() should take arguments and process them.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#4]
In the current implementation, Add() method takes arguments in C++ level but exposed JS layer doesn't take arguments and process them. So, we are just passing hard-coded value and it always returns the same value (3).
https://github.com/lunchclass/bacardi/blob/113a0bbd8f3e154e4212bf55e0d5b6e5c93697ca/examples/calculator_bridge.cc#L28

We should make the function process the arguments and convert types between JS level and C++ level.

**Comment by gogag2** [comment]
If anyone is not assigned yet, can I try it?

**Comment by romandev** [comment]
Go ahead!
