### ISSUE TITLE
Replace "Lunch Class Authors" with "Bacardi Authors" in boilerplates.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#46]
We should replace "Lunch Class Authors" with "Bacardi Authors" in boilerplates of each files.

**Before** ```Copyright (c) 2017 The Lunch Class Authors.```

**After** ```Copyright (c) 2017 The Bacardi Authors.```

**Comment by romandev** [comment]
@taxookim, could you follow this issue up?

**Comment by taxookim** [comment]
yes I can!
