### ISSUE TITLE
Need a test framework for C++ codes.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#47]
We already write some C++ codes but there are no tests for them.
(Currently, only have JS side tests using Mocha.)
So, we should introduce a test framework (e.g. gtest) for C++ codes.

**Comment by yjaeseok** [comment]
Could I try this patch?

----------------------------------------------
I think we need to add a Makefile to apply gtest, and we should add gtest as an external module.
Can I do this? Can you give me some advice on what to do?

**Comment by yjaeseok** [comment]
This issue is closed.
