### ISSUE TITLE
I got some warning message, in first build

### ISSUE THREAD

**Issue by yjaeseok** [lunchclass/bacardi#55]
When I first got the bacardi source download from github and tried it, the following warning occurred.
This warning is likely to be removed.

/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h: In instantiation of ‘static Napi::ClassPropertyDescriptor<T> Napi::ObjectWrap<T>::InstanceMethod(const char*, Napi::ObjectWrap<T>::InstanceMethodCallback, napi_property_attributes, void*) [with T = CalculatorBridge; Napi::ObjectWrap<T>::InstanceMethodCallback = Napi::Value (CalculatorBridge::*)(const Napi::CallbackInfo&)]’:
../examples/calculator_bridge.cc:25:67:   required from here
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::utf8name’ [-Wmissing-field-initializers]
   napi_property_descriptor desc = {};
                                    ^
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::name’ [-Wmissing-field-initializers]
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::method’ [-Wmissing-field-initializers]
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::getter’ [-Wmissing-field-initializers]
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::setter’ [-Wmissing-field-initializers]
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::value’ [-Wmissing-field-initializers]
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::attributes’ [-Wmissing-field-initializers]
/home/jake_ubuntu/Workspace/lunchclass/bacardi/node_modules/node-addon-api/napi-inl.h:2419:36: warning: missing initializer for member ‘napi_property_descriptor::data’ [-Wmissing-field-initializers]

**Comment by romandev** [comment]
Hi, @yjaeseok, this is not our issue. If you want it, you can try to fix it in upstream. :)

**Comment by yjaeseok** [comment]
This is about napo issue??

**Comment by yjaeseok** [comment]
*napi

**Comment by romandev** [comment]
This is not N-API issue and it's a node-addon-api issue. (C++ Wrapper package)

**Comment by yjaeseok** [comment]
ohh.. okay i will try it soon :)
