### ISSUE TITLE
The bacardi.cc should be generated by code generator.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#65]
The bacardi.cc and bacardi.h files are in examples directory currently. The file is used to initialize bridge classes but we are not sure what is added newly in the future. Therefore, we should make it be generated automatically.

**Comment by daehyunjimmy** [comment]
I will handle this issue.

**Comment by romandev** [comment]
Okay, @daehyunjimmy  Go ahead!

**Comment by romandev** [comment]
@daehyunjimmy Are you working on this issue?
If not so, I'll take it?

**Comment by daehyunjimmy** [comment]
I am working on it. if have problems, I will let you know.
Thanks
