### ISSUE TITLE
Should implement constructor in WebIDL.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#70]
In the current implementation, we allow to create object in JS side although there is no constructor definition in WebIDL. It's seems a bug. We should allow to create object with constructor in JS side only if there is an explicit constructor in WebIDL level. To resolve the issue, we should implement constructor feature.

**Comment by romandev** [comment]
@yjaeseok Are you interested in this issue?

**Comment by yjaeseok** [comment]
Yes I am interested in this issue, But i have some question.

Calculator has only function (looks like static function), so user do not want to use constructor as class.
If we were to show the constructor correctly, would we need an example with member variables and functions or inheritance?

**Comment by romandev** [comment]
Hi, @yjaeseok 
We can add a constructor in Calculator example for now as follows:
```webidl
[
    Constructor,
    Constructor(double createdTime)
]
interface Calculator {
    static void print();
    double add(double number1, double number2);
    ...
};
```
Then, our generator should generate glue codes(bridge codes) and then it should eventually call
developer's cpp constructor.
```c++
class Calculator {
 public:
  Calculator() {
    ...
  }

  Calculator(double created_time) {
    ...
  }
};
```

Yes, we might need variables and inheritance but it's not ready yet. We can implement them incrementally. :)

**Comment by yjaeseok** [comment]
Hmm.. 
I have tried many ways It seems that it is hard to apply patch because of lack of understand concept. Could you help me with some advise?
 @romandev

**Comment by yjaeseok** [comment]
How could I get constructor value in template_cpp.njk file?

I think i have to modify idls.ts for idl parsing, but i do not understand how to access constructor parameter like member_info variable.

there is no member_info definition in any files.

**Comment by romandev** [comment]
We might need a new data structure.
For example, we can think the constructor function is a special member of the interface.
It's my own thinking and your design can be different.
```
export interface InterfaceConstructor extends InterfaceMember {
}
```

Also, you can get the information from raw_idl_info.extAttrs.
Please see https://github.com/w3c/webidl2.js#extended-attributes

**Comment by yjaeseok** [comment]
The issue is closed.
