### ISSUE TITLE
We can not use camelCase method name.

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#82]
In the current implementation, we can not use camelCase naming.
For example, if the camelCase() method is defined in interface as follows:
```webidl
interface ExampleInterface {
    void camelCase();
};
```
Our generator generates codes as follows:
```c++
class ExampleInterface {
    void Camelcase();    // This is a bug.
};
```

**Comment by yjaeseok** [comment]
I try this issue by adding filter. please review :+1:

**Comment by romandev** [comment]
@yjaeseok, Can we close this issue? If so, please close this. Thanks!

**Comment by yjaeseok** [comment]
This issue is closed.
