### ISSUE TITLE
Add some badges in README.md

### ISSUE THREAD

**Issue by romandev** [lunchclass/bacardi#95]
We have already two badges. Travis and AppVeyor. But we still need some additional badges such as Slack link and License link.

So, you can just update the following links in README.md:

https://img.shields.io/badge/License-Apache%202.0-yellowgreen.svg
https://img.shields.io/badge/slack-online-green.svg

**Comment by romandev** [comment]
@byeolbit PTAL

**Comment by byeolbit** [comment]
Ok, I’ll take care this issue.
